### ISSUE TITLE
Language Strings in mustache

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#10]
Please also use the language package in mustache e.g. ` {{# str }} helloworld, mod_greeting {{/ str }}` instead of e.g. https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/0d0cb7c7ca4b187fd966c56a8596aabc81d60822/templates/experiences_overview.mustache#L19
[https://docs.moodle.org/dev/Templates#.7B.7B.23_str_.7D.7D]

**Comment by aaronkossler** [comment]
done
