### ISSUE TITLE
Form - max size

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#11]
In all forms use a maximum number of characters which match the length of the field in the database.
https://docs.moodle.org/dev/lib/formslib.php_Form_Definition#text
e.g. 
`$mform->addElement('text', 'name', get_string('forumname', 'forum'), $attributes);`
`$attributes=array('maxlength'=>'55');`
`$mform->addRule('name', null, 'required', null, 'client');`

**Comment by aaronkossler** [comment]
fixed for experience part.
