### ISSUE TITLE
If applicable use predefined get_records function

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#12]
If applicable (not so easy for joins) always use `get_record(s)()` instead of `get_record(s)_sql` this includes some prechecks.
I think the order by clause could also be a param of `get_record(s)()` in
-> step_overview l.34
-> step_admin l.33

Furthermore, no need to state default parameters like` $fields='*', $strictness=IGNORE_MISSING`.

**Comment by david-kost** [comment]
Thank you for raising this issue!
The issue has been resolved with commit #c89aeb9c0684e8da150259dc8a41bfcc4777018b and commit #fa9ccfe7ca755a4c452c4df036e9272c235edd84 (31.01.2021).
