### ISSUE TITLE
Improvement add Navigation Buttons

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#13]
Please think about how to improve the navigation of your plugin. E.g. an admin who adds categories might want to add another category instead of returning to the page so providing a 'Save and return' button, a 'Save and add another category' button and a 'Cancel' button would be nice. 
Another example could be the view of an experience. It would be nice to have a back to the overview and a view next experience button when you look at one specific experience. 
These are only suggestions. Maybe you ask users what kind of navigation they would like to have.

**Comment by aaronkossler** [comment]
added navbar links and correct structure
