### ISSUE TITLE
Step display

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#15]
When looking at the steps I get an exception:

![invalidparametervalue](https://user-images.githubusercontent.com/18289780/106151345-8c24e800-617c-11eb-9975-6a2f79b2d7ec.png)

And the first step is a null object. 

![nullstep](https://user-images.githubusercontent.com/18289780/106151354-8fb86f00-617c-11eb-9563-41ee7977dff3.png)

Please contact me if none of you can reproduce the error.

**Comment by david-kost** [comment]
Thank you for bringing awareness to this issue!
The issue has been resolved with commit #6cf6d5e789e9f36fcea4d0f6a0159cbe582355d6 (28.01.2021).
