### ISSUE TITLE
Predefined experience reports are not displayed

### ISSUE THREAD

**Issue by Laur0r** [wwu-ps-digital-onboarding/moodle-block_onboarding#44]
When I click on one of the experience reports in the list view, it is displayed without any text (see attached screenshot). 
Perhaps this is an error in the csv files. I noticed that the id column is missing in the files. This may have led to wrong interdependencies of the database tables e.g. within the experience_matching the the ids of the column category_id are > 20 but in the database they will start at 1.
![Bildschirmfoto vom 2021-03-05 10-55-37](https://user-images.githubusercontent.com/35337130/110100183-681f7c80-7da2-11eb-8da8-74d75f3eadb6.png)

**Comment by aaronkossler** [comment]
resolved.
