### ISSUE TITLE
Captions difficult to read

### ISSUE THREAD

**Issue by Laur0r** [wwu-ps-digital-onboarding/moodle-block_onboarding#46]
The captions in the block are difficult to read (see attached screenshot)
![Bildschirmfoto vom 2021-03-05 11-05-57](https://user-images.githubusercontent.com/35337130/110115793-e2f29280-7db6-11eb-85a6-ce081801311b.png)
.

**Comment by aaronkossler** [comment]
![image](https://user-images.githubusercontent.com/74201118/110210480-3b1fb680-7ed5-11eb-9591-c9b84c284588.png)

There seems to be a style issue on your end. It should look like this.

**Comment by konstantinlois** [comment]
Should be fixed in 0.2.4
