### ISSUE TITLE
Multiple styles issues

### ISSUE THREAD

**Issue by Laur0r** [wwu-ps-digital-onboarding/moodle-block_onboarding#47]
This are some minor style issues I noticed.
 
Concerning the filtering of experiences:
![Bildschirmfoto vom 2021-03-05 13-44-47](https://user-images.githubusercontent.com/35337130/110117433-20f0b600-7db9-11eb-8879-0fddae8b69ae.png)
![Bildschirmfoto vom 2021-03-05 13-36-14](https://user-images.githubusercontent.com/35337130/110117460-29e18780-7db9-11eb-8a0f-4975b51f4b51.png)

On the guide overview page, the wiki links have an unnecessary horizontal scroll bar which allows for minimal scrolling: 
![Bildschirmfoto vom 2021-03-05 14-19-35](https://user-images.githubusercontent.com/35337130/110121007-1b499f00-7dbe-11eb-86b0-36f78a1850ed.png)

**Comment by aaronkossler** [comment]
resolved with next update
