### ISSUE TITLE
Duplicate file invocation

### ISSUE THREAD

**Issue by Laur0r** [wwu-ps-digital-onboarding/moodle-block_onboarding#49]
One of the two constant invocations should be enough:
https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/6ad186aa8464010b9b69d86dd31bc20723991d76/classes/forms/experiences_report_form.php#L21
https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/6ad186aa8464010b9b69d86dd31bc20723991d76/classes/forms/experiences_report_form.php#L23

**Comment by aaronkossler** [comment]
Solved. Will be added in next release version.
