### ISSUE TITLE
Use update_record

### ISSUE THREAD

**Issue by Laur0r** [wwu-ps-digital-onboarding/moodle-block_onboarding#51]
Please use update_record instead of deleting and inserting records when they are edited. It is more efficient and existing ids can be reused.

https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/6ad186aa8464010b9b69d86dd31bc20723991d76/classes/experiences_lib.php#L22

And aren't all experiences already deleted at this point? 
https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/6ad186aa8464010b9b69d86dd31bc20723991d76/classes/experiences_lib.php#L66

**Comment by aaronkossler** [comment]
resolved with new update
