### ISSUE TITLE
Not Empty check in Steps

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#7]
Please check in `classes/step_view_data_functions.php` in line 77 whether no step exists. Ideally, give the user a warning or do not show content in case no step exists. Currently, an error is thrown: 
![dmlwriteexception](https://user-images.githubusercontent.com/18289780/105965002-39b3d080-6083-11eb-8653-852a2be1cceb.png)

**Comment by david-kost** [comment]
Thank you for raising this issue!
The issue has been resolved with commit #7b79b467ea060d254fa4bf6b4e82ca3d0a932e1e (31.01.2021).

**Comment by NinaHerrmann** [comment]
For future references, if you use #[number] in this case #7 in your commit message the commit is automatically linked :)
