### ISSUE TITLE
Make Styles specific

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#73]
With code like this:
https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/e7062d69482e4b833786103a7bb1ff2a499cab64/styles.css#L18

you add this rule to **every** element on the site, need to make them specific for your block e.g. `.wiki-overview .title`.
The same holds true for other style rules.

**Comment by david-kost** [comment]
thank you for raising this issue!
fixed the issue with recent commits 👍
