### ISSUE TITLE
Grunt installation

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#8]
_If you have previous node versions:
check it with `nvm ls` if the version is < 14.15.0 please uninstall it `nvm uninstall [yourversionnumber]`_
### install nvm on your system
`nvm install`
`nvm use`

`nvm alias default v14.15.0`

### Install grunt

run the following commands from your Moodle directory:

`npm install`

This may mention vulnerabilities, that's fine and doesn't apply.

`npm install -g grunt-cli`
## Go in your plugin (blocks/onboarding/amd) and execute
`grunt`
this will give you an error as line 27 & 49 are missing a semicolon. 

Remove all grunt, package.json etc. files.

 _[https://docs.moodle.org/dev/Grunt#Running_grunt, https://docs.moodle.org/dev/Javascript_Modules#Install_grunt]_

**Comment by NinaHerrmann** [comment]
Also please remove old `block_` files in step and experiences

**Comment by david-kost** [comment]
Thank you for informing the team about this issue!
The issue has been resolved with commit #8b8bc2a311af899e190097859673a1ebabecf2d6 (01.02.2021). The grunt- and package-files will be removed with the final release.
