### ISSUE TITLE
Not null checks in add experience

### ISSUE THREAD

**Issue by NinaHerrmann** [wwu-ps-digital-onboarding/moodle-block_onboarding#9]
In case no degree program or no categories are defined include checks which give a warning (https://github.com/wwu-ps-digital-onboarding/moodle-block_onboarding/blob/0d0cb7c7ca4b187fd966c56a8596aabc81d60822/classes/output/renderables/experiences_overview.php#L38) or even forbid to add an experience.

**Comment by aaronkossler** [comment]
Added an Error Page if there is not enough data to create an experience.
